#!/usr/bin/env python3
"""
Email Configuration Setup for UIC Patent Portal
Run this script to configure email settings for password reset functionality.
"""

import os
import getpass

def setup_gmail():
    """Setup Gmail SMTP configuration"""
    print("\n📧 Gmail Setup")
    print("=" * 50)
    print("To use Gmail, you need:")
    print("1. Enable 2-Factor Authentication on your Gmail account")
    print("2. Generate an 'App Password' (not your regular password)")
    print("3. Use the App Password below")
    print("\nHow to get Gmail App Password:")
    print("• Go to: https://myaccount.google.com/security")
    print("• Click: 2-Step Verification → App passwords")
    print("• Generate password for 'Mail'")
    print("• Use the 16-character password below")
    
    email = input("\nEnter your Gmail address: ").strip()
    if not email.endswith('@gmail.com'):
        print("⚠️  Warning: This doesn't look like a Gmail address")
    
    app_password = getpass.getpass("Enter your Gmail App Password (16 characters): ").strip()
    
    return {
        'MAIL_SERVER': 'smtp.gmail.com',
        'MAIL_PORT': 587,
        'MAIL_USE_TLS': True,
        'MAIL_USERNAME': email,
        'MAIL_PASSWORD': app_password
    }

def setup_outlook():
    """Setup Outlook/Hotmail SMTP configuration"""
    print("\n📧 Outlook/Hotmail Setup")
    print("=" * 50)
    
    email = input("Enter your Outlook/Hotmail address: ").strip()
    password = getpass.getpass("Enter your password: ").strip()
    
    return {
        'MAIL_SERVER': 'smtp-mail.outlook.com',
        'MAIL_PORT': 587,
        'MAIL_USE_TLS': True,
        'MAIL_USERNAME': email,
        'MAIL_PASSWORD': password
    }

def setup_custom():
    """Setup custom SMTP configuration"""
    print("\n📧 Custom SMTP Setup")
    print("=" * 50)
    
    server = input("Enter SMTP server (e.g., smtp.yourdomain.com): ").strip()
    port = input("Enter SMTP port (usually 587 or 465): ").strip()
    use_tls = input("Use TLS? (y/n): ").strip().lower() == 'y'
    email = input("Enter your email address: ").strip()
    password = getpass.getpass("Enter your password: ").strip()
    
    return {
        'MAIL_SERVER': server,
        'MAIL_PORT': int(port),
        'MAIL_USE_TLS': use_tls,
        'MAIL_USERNAME': email,
        'MAIL_PASSWORD': password
    }

def test_email_config(config):
    """Test email configuration"""
    print("\n🧪 Testing Email Configuration...")
    
    try:
        from flask import Flask
        from flask_mail import Mail, Message
        
        # Create test Flask app
        app = Flask(__name__)
        app.config.update(config)
        app.config['MAIL_DEFAULT_SENDER'] = config['MAIL_USERNAME']
        
        mail = Mail(app)
        
        with app.app_context():
            # Create test message
            msg = Message(
                subject='Test Email - UIC Patent Portal',
                recipients=[config['MAIL_USERNAME']],
                body='This is a test email from UIC Patent Portal. Email configuration is working!',
                html='<h2>✅ Email Configuration Test</h2><p>This is a test email from <strong>UIC Patent Portal</strong>.</p><p>Email configuration is working correctly!</p>'
            )
            
            mail.send(msg)
            print("✅ Test email sent successfully!")
            print(f"📧 Check your inbox: {config['MAIL_USERNAME']}")
            return True
            
    except Exception as e:
        print(f"❌ Email test failed: {str(e)}")
        return False

def save_config(config):
    """Save configuration to environment file"""
    env_content = f"""# Email Configuration for UIC Patent Portal
# Generated by setup_email.py

MAIL_SERVER={config['MAIL_SERVER']}
MAIL_PORT={config['MAIL_PORT']}
MAIL_USE_TLS={'True' if config['MAIL_USE_TLS'] else 'False'}
MAIL_USERNAME={config['MAIL_USERNAME']}
MAIL_PASSWORD={config['MAIL_PASSWORD']}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n💾 Configuration saved to .env file")
    print("🚀 You can now run your Flask app with email support!")

def main():
    print("🔧 UIC Patent Portal - Email Setup")
    print("=" * 50)
    print("This will configure email settings for password reset functionality.")
    
    print("\nChoose your email provider:")
    print("1. Gmail (Recommended)")
    print("2. Outlook/Hotmail")
    print("3. Custom SMTP Server")
    
    choice = input("\nEnter your choice (1-3): ").strip()
    
    if choice == '1':
        config = setup_gmail()
    elif choice == '2':
        config = setup_outlook()
    elif choice == '3':
        config = setup_custom()
    else:
        print("❌ Invalid choice. Exiting.")
        return
    
    print(f"\n📋 Configuration Summary:")
    print(f"Server: {config['MAIL_SERVER']}:{config['MAIL_PORT']}")
    print(f"Email: {config['MAIL_USERNAME']}")
    print(f"TLS: {config['MAIL_USE_TLS']}")
    
    # Test configuration
    test_choice = input("\n🧪 Test email configuration? (y/n): ").strip().lower()
    if test_choice == 'y':
        if test_email_config(config):
            save_config(config)
        else:
            print("❌ Email test failed. Please check your settings and try again.")
    else:
        save_config(config)
    
    print("\n🎉 Email setup complete!")
    print("💡 To use the configuration:")
    print("   1. Make sure .env file is in your backend directory")
    print("   2. Run: python app.py")
    print("   3. Test password reset functionality")

if __name__ == "__main__":
    main()